### ISSUE TITLE
Sprint 2 - Equipe Requisitos

### ISSUE THREAD

**Issue by typejulio** [mdsreq-fga-unb/2023.1-Remediario#14]
# Sprint 2 - Equipe Requisitos

## Tarefas

| Código | Descrição           | Critério de aceitação                       |
| :----: | :------------------ | :------------------------------------------ |
|   01   | Criar Backlog | Estar no mkdocs |
|   02   | Analisar e Atualizar Mural  | Mural revisado e atualizado e estar inserido no markdown |
|   03   | Alteração de US e definir MVP | Revisado e aprovado pela cliente e estar inserido no markdown |

- [x] Tarefa 01
- [x] Tarefa 02
- [x] Tarefa 03

## Responsáveis

| Assignees  |
| :--------: |
| @RodrigoWright  |
| @CarlosEduardoMendesdeMesquita  |

**Comment by RodrigoWright** [comment]
Backlog.mb no mkdocs
