### ISSUE TITLE
Correção da unidade 1

### ISSUE THREAD

**Issue by typejulio** [mdsreq-fga-unb/2023.1-Remediario#16]
## Tarefas

| Código | Descrição           | Critério de aceitação                       |
| :----: | :------------------ | :------------------------------------------ |
|   01   | Issue #10 e Issue #9  | Alterado no mkdocs |
|   02   | Issue #8                        | Alterado no mkdocs |
|   03   | Issue #7                        | Alterado no mkdocs |
|   04   | Issue #6                        | Alterado no mkdocs |
|   05   | Issue #5                        | Alterado no mkdocs |

- [x] Tarefa 01 @RodrigoWright
- [x] Tarefa 02 @CarlosEduardoMendesdeMesquita
- [x] Tarefa 03 @Mateuszinnn
- [x] Tarefa 04 @typejulio
- [x] Tarefa 05 @Luanmq

## Responsáveis

| Assignees  |
| :--------: |
| @RodrigoWright |
| @CarlosEduardoMendesdeMesquita |
| @Mateuszinnn |
| @typejulio |
| @Luanmq |

**Comment by Luanmq** [comment]
Tarefa 5 feita na commit: https://github.com/mdsreq-fga-unb/2023.1-Remediario/commit/67f2bbead07b180f223fc5140dd9444853a3abe7

**Comment by RodrigoWright** [comment]
Todas as alterações foram feitas
