### ISSUE TITLE
Estudar onde serão armazenados os dados(Equipe Requisitos)

### ISSUE THREAD

**Issue by typejulio** [mdsreq-fga-unb/2023.1-Remediario#31]
## Tarefas

| Código | Descrição           | Critério de aceitação                       |
| :----: | :------------------ | :------------------------------------------ |
|   01   | Definir o método de persistência de dados | X |

- [x] Tarefa 01 

## Responsáveis

| Assignees  |
| :--------: |
| @RodrigoWright |
| @CarlosEduardoMendesdeMesquita  |

**Comment by RodrigoWright** [comment]
Ferramentas:

| Método | Escolha | Motivo |
| --------- | -------- | -------- |
| FireBase | Não      | Complicações no funcionamento Ofline |
| SQLite    | Não      | Desenvolvimento de um banco de dados local, embora funcione de forma ofline não é necessário (overkill) |
| AsyncStorage | Sim | Simples e funciona offline, salva localmente os arquivos em texto no celular |

Escolhemos o AsyncStorage por ser simples e atender a demanda do projeto. link: https://react-native-async-storage.github.io/async-storage/docs/usage/

**Comment by RodrigoWright** [comment]
Ambiente definido já.
