### ISSUE TITLE
(EP04 - US21) Eu como usuário quero visualizar o registro de todos os remédios que tomei no dia para poder ter o controle do uso dos meus medicamentos.

### ISSUE THREAD

**Issue by typejulio** [mdsreq-fga-unb/2023.1-Remediario#52]
(EP04 - US21) Eu como usuário quero visualizar o registro de todos os remédios que tomei no dia para poder ter o controle do uso dos meus medicamentos.

- Eu quero poder diferenciar visualmente (pela coloração) os remédios que eu tomei dos que eu não tomei.
- Eu quero ver o horário que tomei o remédio.
- [x] BackEnd
- [x] FrontEnd
- [x] Integração

**Comment by RodrigoWright** [comment]
Não implementada
