### ISSUE TITLE
(EP03 - US12) Eu como usuário quero editar medicamentos, para altera-los ao meu gosto.

### ISSUE THREAD

**Issue by typejulio** [mdsreq-fga-unb/2023.1-Remediario#69]

**Comment by Mateuszinnn** [comment]
## Critérios de aceitação:

- [ ] O usuário deve ter a opção de editar medicamentos existentes.
- [ ] A funcionalidade de edição deve estar facilmente acessível e visível para o usuário.
- [ ] O usuário deve ser capaz de editar informações básicas do medicamento, como nome, dosagem e horários de administração.
- [ ] O sistema deve permitir ao usuário adicionar informações adicionais relevantes, como notas, instruções especiais ou restrições.
- [ ] O usuário deve ser capaz de salvar as alterações feitas no medicamento.
- [ ] As alterações feitas nos medicamentos devem ser refletidas imediatamente em todas as partes do aplicativo onde os medicamentos são exibidos.
- [ ] O sistema deve garantir a consistência e validade dos dados inseridos pelo usuário ao editar os medicamentos.
