### ISSUE TITLE
(EP02 - US06) Eu como usuário quero programar a notificação para tocar novamente daqui 5 minutos para eu poder me planejar melhor.

### ISSUE THREAD

**Issue by typejulio** [mdsreq-fga-unb/2023.1-Remediario#71]

**Comment by Mateuszinnn** [comment]
Critérios de aceitação:

- [ ] O usuário deve ter a opção de ativar a notificação para tocar novamente em 5 minutos.
- [ ] A notificação deve incluir um botão para ativar a repetição da notificação em 5 minutos.
- [ ] Ao selecionar a opção de repetição, a notificação deve ser programada para tocar novamente exatamente após 5 minutos.
- [ ] A repetição da notificação em 5 minutos deve funcionar corretamente mesmo se o aplicativo estiver em segundo plano ou o dispositivo estiver bloqueado.

**Comment by Luanmq** [comment]
Botão de Adiar implementado
