### ISSUE TITLE
Criar os critérios de aceitação das US's do MVP 2.

### ISSUE THREAD

**Issue by typejulio** [mdsreq-fga-unb/2023.1-Remediario#72]

**Comment by Mateuszinnn** [comment]
## Critérios de aceitação:

- [ ] (EP03 - US17) Eu como usuário quero receber uma notificação quando possuir apenas 3 dosagens para pedir para o médico uma nova receita.
- [ ] (EP03 - US12) Eu como usuário quero editar medicamentos, para altera-los ao meu gosto. 
- [ ] (EP02 - US06) Eu como usuário quero programar a notificação para tocar novamente daqui 5 minutos para eu poder me planejar melhor.

**Comment by Mateuszinnn** [comment]
Critérios de aceitação da US17 feito. #70 
Critérios de aceitação da US12 feito. #69

**Comment by Mateuszinnn** [comment]
Critérios de aceitação da US06 feito. #71

**Comment by Mateuszinnn** [comment]
Critérios de aceitação da US08 feito. #78 
Critérios de aceitação da US15 feito. #79 
Critérios de aceitação da US18 feito. #80 
Critérios de aceitação da US19 feito. #81

**Comment by Mateuszinnn** [comment]
Critérios de aceitação da US20 feito. #82
