### ISSUE TITLE
Resolver pendências das unidades passadas

### ISSUE THREAD

**Issue by Mateuszinnn** [mdsreq-fga-unb/2023.1-Remediario#73]
## Em Visão de produto

- [x] Atualizar lições aprendidas
- [x] Atualizar gerenciamento de riscos
- [x] Atualizar documentação das sprints (colocar a planning da 7 na 7, da 8 na 8...) - Julio
- [x] Na retrospectiva criar um plano de ação contra os riscos existentes - Rodrigo

## No aplicativo

- [x] Fazer o critério de aceitação da história 13
- [x] Fazer o critério de aceitação da história 21 - Carlos e Luan
- [x] Acrescentar critério de aceitação na história 09

## Pendencias da entrega da unidade 3

- [x] Fazer o BDD
- [x] Fazer o vídeo de apresentação da unidade - Todos

**Comment by Mateuszinnn** [comment]
lições aprendidas atualizadas no commit 7796921.

**Comment by Mateuszinnn** [comment]
gerenciamento de risco atualizado no commit 89f1e04.

**Comment by Mateuszinnn** [comment]
critério de aceitação da história 13 resolvido no commit c413d6c.

**Comment by Mateuszinnn** [comment]
BDD finalizado no commit 0dc1141.

**Comment by typejulio** [comment]
fazer os videos de apresentação da unidade 1 e 3, ou só da unidade 3 ?
