### ISSUE TITLE
US08: Eu como usuário quero visualizar um temporizador em contagem regressiva após confirmar na tela de confirmação para saber quando devo tomar minha próxima dose.

### ISSUE THREAD

**Issue by Mateuszinnn** [mdsreq-fga-unb/2023.1-Remediario#78]
## Critérios de aceitação:

- [x] Após confirmar na tela de confirmação para tomar a dose do medicamento, o usuário na tela de meus remédios e remédio dos dia deve ver uma tela que exibe um temporizador em contagem regressiva.
- [x] O temporizador deve ser claramente visível para o usuário e exibido de forma intuitiva.
- [x] O tempo exibido no temporizador deve corresponder ao intervalo de tempo restante até a próxima dose.
- [x] O temporizador deve ser atualizado em tempo real, mostrando a contagem regressiva de forma precisa e consistente.
- [x] O sistema deve considerar eventuais atrasos ou adiantamentos na administração da dose e ajustar o temporizador de acordo.

**Comment by typejulio** [comment]
bug

**Comment by typejulio** [comment]
resolvido o bug do timer, atende todos os critérios de aceitação 😎👍
